name: Validate accuracy (de421/2000-2050/3)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 3.4.1

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Validate accuracy with kernel de421 from 2000 to 2050 for target 3
        run: bundle exec rake validate_accuracy date=2000 kernel=de421 target=3
