name: Validate accuracy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate (${{ matrix.kernel }}/2000-2050/${{ matrix.target }})
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
      - name: Validate accuracy of Ephem against multiple kernels
        run: bundle exec rake validate_accuracy:all
